// @ts-check

// This file is automatically generated by scripts/generate-sidebar.js
// Do not edit this file manually.

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    // 按文件修改时间排序的文档列表（最新修改的在前）
    '3dapp/vfx-grace-corals-collection',
    '3dapp/substance-3d-modeler',
    '3dapp/premiere-pro-400-vertical-transitions',
    '3dapp/ae-script-han-motion-type',
    '3dapp/ae-template-diamond-logo-opener',
    '3dapp/physical-grass-scatter-and-draw',
    '3dapp/history-timeline',
    '3dapp/fcpx-smoke-transitions',
    '3dapp/archexteriors-vol-32',
    '3dapp/ray-dynamic-texture',
    '3dapp/houdini-21',
    '3dapp/face-3d',
    '3dapp/blender-simple-n-panel',
    '3dapp/fcpx-minimal-lower-thirds',
    '3dapp/retro-vibes-transition',
    '3dapp/after-keying',
    '3dapp/circuitfx',
    '3dapp/shade-it',
    '3dapp/blender-realistic-3d-character-creation',
    '3dapp/gaussian-splatting',
    '3dapp/auto-crop-3',
    '3dapp/aescripts-voodoo-template',
  ],
};

export default sidebars;
