// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  '3dappSidebar': [
    {
      type: 'category',
      label: '3DApp',
      items: [{type: 'autogenerated', dirName: '3dapp'}],
      link: {
        type: 'generated-index',
        title: '3D Applications',
        description: 'Resources for 3D Applications including plugins, assets, and tutorials.',
        slug: '/category/3dapp'
      }
    },
  ],
  'tutorialSidebar': [
    {
      type: 'category',
      label: 'Tutorial',
      items: [{type: 'autogenerated', dirName: 'tutorial'}],
      link: {
        type: 'generated-index',
        title: 'Tutorials',
        description: 'Learn how to use our resources and tools effectively.',
        slug: '/category/tutorial'
      }
    },
  ],
  'gallerySidebar': [
    {
      type: 'category',
      label: 'Gallery',
      items: [{type: 'autogenerated', dirName: 'gallery'}],
      link: {
        type: 'generated-index',
        title: 'Gallery',
        description: 'A gallery of amazing creations.',
        slug: '/category/gallery'
      }
    },
  ],
  'compSidebar': [
    {
      type: 'category',
      label: 'Comp',
      items: [{type: 'autogenerated', dirName: 'comp'}],
      link: {
        type: 'generated-index',
        title: 'Compositing Resources',
        description: 'Resources for compositing software and tools.',
        slug: '/category/comp'
      }
    },
 ],
  'aeSidebar': [
    {
      type: 'category',
      label: 'AE',
      items: [{type: 'autogenerated', dirName: 'ae'}],
      link: {
        type: 'generated-index',
        title: 'After Effects Resources',
        description: 'Resources for Adobe After Effects including scripts, templates, and plugins.',
        slug: '/category/ae'
      }
    },
 ],
  'blenderSidebar': [
    {
      type: 'category',
      label: 'Blender',
      items: [{type: 'autogenerated', dirName: 'blender'}],
      link: {
        type: 'generated-index',
        title: 'Blender Resources',
        description: 'Resources for Blender including addons, tutorials, and assets.',
        slug: '/category/blender'
      }
    },
 ],
  'textureSidebar': [
    {
      type: 'category',
      label: 'Texture',
      items: [{type: 'autogenerated', dirName: 'texture'}],
      link: {
        type: 'generated-index',
        title: 'Texture Resources',
        description: 'Resources for textures including PBR materials, Substance tools, and UV unwrapping.',
        slug: '/category/texture'
      }
    },
 ],
  'modelSidebar': [
    {
      type: 'category',
      label: 'Model',
      items: [{type: 'autogenerated', dirName: 'model'}],
      link: {
        type: 'generated-index',
        title: '3D Models',
        description: 'Collection of 3D models including characters, environments, and assets.',
        slug: '/category/model'
      }
    },
 ],
  'simSidebar': [
    {
      type: 'category',
      label: 'Sim',
      items: [{type: 'autogenerated', dirName: 'sim'}],
      link: {
        type: 'generated-index',
        title: 'Simulation Resources',
        description: 'Resources for simulation tools and software.',
        slug: '/category/sim'
      }
    },
 ],
};

export default sidebars;
