// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  '3dappSidebar': [
    {
      type: 'category',
      label: '3DApp',
      items: [{type: 'autogenerated', dirName: '3dapp'}],
      link: {
        type: 'generated-index',
        title: '3D Applications',
        description: 'Resources for 3D Applications including plugins, assets, and tutorials.',
        slug: '/category/3dapp'
      }
    },
  ],
  'tutorialSidebar': [
    {
      type: 'category',
      label: 'Tutorial',
      items: [{type: 'autogenerated', dirName: 'tutorial'}],
      link: {
        type: 'generated-index',
        title: 'Tutorials',
        description: 'Learn how to use our resources and tools effectively.',
        slug: '/category/tutorial'
      }
    },
  ],
  'gallerySidebar': [
    {
      type: 'category',
      label: 'Gallery',
      items: [{type: 'autogenerated', dirName: 'gallery'}],
      link: {
        type: 'generated-index',
        title: 'Gallery',
        description: 'A gallery of amazing creations.',
        slug: '/category/gallery'
      }
    },
  ],
};

export default sidebars;
