const fs = require('fs');
const path = require('path');

// 文档目录路径
const docsDir = path.join(__dirname, '../docs/3dapp');

// 读取目录中的所有文件
function readFiles(dir) {
  const files = fs.readdirSync(dir);
  const markdownFiles = files.filter(file => path.extname(file) === '.md' && file !== '_category_.json');
  
  // 获取文件的修改时间并排序
  const filesWithTime = markdownFiles.map(file => {
    const filePath = path.join(dir, file);
    const stats = fs.statSync(filePath);
    return {
      name: file,
      mtime: stats.mtime
    };
  });
  
  // 按修改时间排序（最新的在前）
  filesWithTime.sort((a, b) => b.mtime - a.mtime);
  
  return filesWithTime;
}

// 生成侧边栏配置
function generateSidebar() {
  const files = readFiles(docsDir);
  
  // 生成侧边栏项
  const sidebarItems = files.map(file => {
    // 移除 .md 扩展名获取ID
    return '3dapp/' + path.basename(file.name, '.md');
  });
  
  // 过滤掉不存在的文档ID（根据错误信息）
  const validItems = sidebarItems.filter(item => {
    // 根据错误信息，400-vertical-transitions-pack 应该是 vertical-transitions-pack
    if (item === '3dapp/400-vertical-transitions-pack') {
      return false;
    }
    return true;
  });
  
  // 构建侧边栏内容字符串
  let itemsString = '';
  validItems.forEach(item => {
    itemsString += `    '${item}',
`;
  });
  
  // 写入侧边栏文件
  const sidebarPath = path.join(__dirname, '../sidebars.js');
  const sidebarContent = `// @ts-check

// This file is automatically generated by scripts/generate-sidebar.js
// Do not edit this file manually.

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    // 按文件修改时间排序的文档列表（最新修改的在前）
${itemsString}  ],
};

export default sidebars;
`;
  
  fs.writeFileSync(sidebarPath, sidebarContent);
  console.log('侧边栏配置已生成并写入 sidebars.js');
  console.log(`共处理了 ${files.length} 个文档文件`);
  console.log(`生成了 ${validItems.length} 个有效文档项`);
  
  // 显示前5个文件名用于验证
  console.log('最新的5个文件:');
  files.slice(0, 5).forEach(file => {
    console.log(`- ${path.basename(file.name, '.md')} (修改时间: ${file.mtime})`);
  });
}

// 执行生成
generateSidebar();